version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    network_mode: bridge
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
  
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/data/redis
    ports:
      - '6379:6379'

  app:
    container_name: news-app
    restart: always
    build: .
    ports:
      - '5678:5678'
    environment:
        APP_PORT: '5678'
        MONGO_URI: mongodb://mongo:27017
        REDIS_PORT: 6379
        REDIS_HOST: redis
        NODE_ENV: prod

    network_mode: bridge
    depends_on:
      - mongo
    links:
      - mongo

volumes: 
  mongo: {}